# Generated by Django 6.0.6 on 2026-07-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price_from',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_unit',
        ),
    ]
