# Generated by Django 6.0.6 on 2026-07-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_ecommerce_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hero_image',
            field=models.CharField(blank=True, max_length=200, verbose_name='Изображение для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_image',
            field=models.CharField(blank=True, max_length=200, verbose_name='Изображение'),
        ),
    ]
